#ifndef _CURE_H
#define _CURE_H

/******************************************************************************
	Name : CURE
	Desc : Flying UV Cure Extensions for IMS5000
******************************************************************************/
// IMPCURESTEP Support
void CURESTEPInit(IMPMARK *m);
BOOL CALLBACK CURESTEPEDITDP(HWND hdlg,UINT message,WPARAM wP,LPARAM lP);

#endif // _CURE_H

